### ISSUE TITLE
panic: runtime error: index out of range [15] with length 0

### ISSUE THREAD

**Issue by jaiswalakshansh** [projectdiscovery/dnsx#494]
---
title: Error: Index out of range in dnsx
labels: bug
---

### Description
I encountered an error while running `dnsx` with the following command:
```shell
echo AS17012 | dnsx -silent -resp-only -ptr
panic: runtime error: index out of range [15] with length 0

goroutine 1 [running]:
github.com/projectdiscovery/mapcidr.ipNetToRange({{0x0, 0x0, 0x0}, {0x140009accf0, 0x10, 0x10}})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.9/ip.go:289 +0x4c4
github.com/projectdiscovery/mapcidr.partitionCIDR({{0x140009acc80, 0x10, 0x10}, {0x140009acc90, 0x10, 0x10}}, {{0x0, 0x0, 0x0}, {0x140009accf0, ...}})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.9/ip.go:622 +0x190
github.com/projectdiscovery/mapcidr.rangeToCIDRs({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.9/ip.go:599 +0x568
github.com/projectdiscovery/mapcidr.GetCIDRFromIPRange({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.9/ip.go:1058 +0xe0
github.com/projectdiscovery/asnmap/libs.GetCIDR({0x140003f0b60, 0xb, 0x140005ae012?})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/asnmap@v1.0.5/libs/cidr.go:12 +0x108
github.com/projectdiscovery/mapcidr/asn.GetCIDRsForASNNum({0x140005ae010?, 0x10109efa8?})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.9/asn/asn.go:35 +0x64
github.com/projectdiscovery/mapcidr/asn.GetIPAddressesAsStream({0x140005ae010?, 0x7?})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.9/asn/asn.go:52 +0x20
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).prepareInput(0x14000472be0)
	/home/runner/work/dnsx/dnsx/internal/runner/runner.go:297 +0x444
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).run(0x14000472be0)
	/home/runner/work/dnsx/dnsx/internal/runner/runner.go:429 +0x28
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).Run(0x1400051eb40?)
	/home/runner/work/dnsx/dnsx/internal/runner/runner.go:425 +0x38
main.main()
	/home/runner/work/dnsx/dnsx/cmd/dnsx/dnsx.go:39 +0x130
```

**Comment by ehsandeep** [comment]
@jaiswalakshansh fixed in latest release - https://github.com/projectdiscovery/dnsx/releases/tag/v1.1.6
