### ISSUE TITLE
[issue] Invalid memory address crash

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/dnsx#70]
**Reported by**
`mightocho` on discord.

**dnsx version**

```
v1.0.3
```

**CMD to replicate:-**

```
echo hackerone.com | dnsx -silent -r 109.228.25.186,158.43.128.72,194.187.251.67,37.152.45.194,188.227.240.58,158.43.240.4,212.118.241.33,88.208.211.65,88.208.229.248,109.228.14.101,162.13.11.127,88.208.218.166,178.62.57.141,5.253.114.91,154.32.107.18,154.32.109.18,158.43.192.1,158.43.240.3,8.8.8.8
```

**Crash details**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102a09588]

goroutine 1 [running]:
github.com/projectdiscovery/dnsx/internal/runner.fileExists(0x16d6bb9b6, 0x106, 0x0)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.0.3/internal/runner/util.go:17 +0x88
github.com/projectdiscovery/dnsx/internal/runner.New(0x1400015e3f0, 0x300000002, 0x14000121f28, 0x10274a8a8)
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.0.3/internal/runner/runner.go:42 +0x80
main.main()
	/Users/ehsandeep/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.0.3/cmd/dnsx/dnsx.go:12 +0x24
```

**Comment by ehsandeep** [comment]
Note:- 
- Crash is only reproducible when we have `8.8.8.8` along with other resolves in the input.
- `8.8.8.8` is part of the default list of resolvers dnsx uses.
